# ------------------- data for the treectrl--------------------
# when change treeApi, must change processreport.GetTestModule
treeBasicApi = [
    "AP_CLEAR_CHAN",
    [
        "assoc_clear_sta_2g",
        "assoc_clear_sta_5g",
    ],
    'AP_CLEAR_LOW',
    [
        "assoc_clear_sta_2g",
        "assoc_clear_sta_5g",
    ],
    'AP_CLEAR_MID',
    [
        "assoc_clear_sta_2g",
        "assoc_clear_sta_5g",
    ],
    'AP_CLEAR_HIGH',
    [
        "assoc_clear_sta_2g",
        "assoc_clear_sta_5g",
    ],
    "AP_CLEAR_LOW_TXPOWER",
    [
        "autochan_txpower_2g",
        "autochan_txpower_5g",
        "chan1_txpower_2g",
        "chan6_txpower_2g",
        "chan11_txpower_2g",
        "chan13_txpower_2g",
        "chan36_txpower_5g",
        "chan52_txpower_5g",
        "chan149_txpower_5g",
        "chan165_txpower_5g",
    ],
    "AP_CLEAR_MID_TXPOWER",
    [
        "autochan_txpower_2g",
        "autochan_txpower_5g",
        "chan1_txpower_2g",
        "chan6_txpower_2g",
        "chan11_txpower_2g",
        "chan13_txpower_2g",
        "chan36_txpower_5g",
        "chan52_txpower_5g",
        "chan149_txpower_5g",
        "chan165_txpower_5g",
    ],
    "AP_CLEAR_HIGH_TXPOWER",
    [
        "autochan_txpower_2g",
        "autochan_txpower_5g",
        "chan1_txpower_2g",
        "chan6_txpower_2g",
        "chan11_txpower_2g",
        "chan13_txpower_2g",
        "chan36_txpower_5g",
        "chan52_txpower_5g",
        "chan149_txpower_5g",
        "chan165_txpower_5g",
    ],
    "AP_CLEAR_CHANSELECTION",
    [
        "chanselection_2g",
        "chanselection_5g",
    ],

    'AP_PSK2_CHAN',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk2_sta_5g',
    ],

    'AP_MIXEDPSK_CHAN',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_MIXEDPSK_CHAN_BW80',
    [
        "assoc_psk2_sta_5g",
        "assoc_psk_sta_5g",
        "assoc_tkippsk2_sta_5g",
        "assoc_tkippsk_sta_5g",
    ],
    'AP_MIXEDPSK_CHAN_BW40',
    [
        "assoc_psk2_sta_2g",
        "assoc_psk_sta_2g",
        "assoc_tkippsk2_sta_2g",
        "assoc_tkippsk_sta_2g",
        "assoc_psk2_sta_5g",
        "assoc_psk_sta_5g",
        "assoc_tkippsk2_sta_5g",
        "assoc_tkippsk_sta_5g",
    ],
    'AP_MIXEDPSK_CHAN_BW20',
    [
        "assoc_psk2_sta_2g",
        "assoc_psk_sta_2g",
        "assoc_tkippsk2_sta_2g",
        "assoc_tkippsk_sta_2g",
        "assoc_psk2_sta_5g",
        "assoc_psk_sta_5g",
        "assoc_tkippsk2_sta_5g",
        "assoc_tkippsk_sta_5g",
    ],
    "AP_MIXEDPSK_CHAN_SSIDSPEC",
    [
        'assoc_psk2_sta_ssidspec_2g',
        'assoc_psk_sta_ssidspec_2g',
        'assoc_tkippsk2_sta_ssidspec_2g',
        'assoc_tkippsk_sta_ssidspec_2g',
        'assoc_psk2_sta_ssidspec_5g',
        'assoc_psk_sta_ssidspec_5g',
        'assoc_tkippsk2_sta_ssidspec_5g',
        'assoc_tkippsk_sta_ssidspec_5g',
    ],
    "AP_MIXEDPSK_CHAN_KEYSPEC",
    [
        'assoc_psk2_sta_keyspec_2g',
        'assoc_psk_sta_keyspec_2g',
        'assoc_tkippsk2_sta_keyspec_2g',
        'assoc_tkippsk_sta_keyspec_2g',
        'assoc_psk2_sta_keyspec_5g',
        'assoc_psk_sta_keyspec_5g',
        'assoc_tkippsk2_sta_keyspec_5g',
        'assoc_tkippsk_sta_keyspec_5g',
    ],
    "AP_MIXEDPSK_CHAN_SSIDCHINESE",
    [
        "assoc_psk2_sta_ssidchinese_2g",
        'assoc_psk_sta_ssidchinese_2g',
        'assoc_tkippsk2_sta_ssidchinese_2g',
        'assoc_tkippsk_sta_ssidchinese_2g',
        'assoc_psk2_sta_ssidchinese_5g',
        'assoc_psk_sta_ssidchinese_5g',
        'assoc_tkippsk2_sta_ssidchinese_5g',
        'assoc_tkippsk_sta_ssidchinese_5g',
    ],
    'AP_SSIDHIDE',
    [
        'ap_clear_ssidhide_2g',
        'ap_clear_ssidhide_5g',
        'ap_psk2_ssidhide_2g',
        'ap_psk2_ssidhide_5g',
        'ap_mixedpsk_ssidhide_2g',
        'ap_mixedpsk_ssidhide_5g',
    ],
    'AP_MIXEDPSK_SSIDHIDE',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],

]

treeGuestWifiApi = [
    'AP_GUEST_CLEAR',
    [
        'assoc_clear_sta_guest',
    ],

    'AP_GUEST_PSK2',
    [
        'assoc_psk2_sta_guest',
    ],

    'AP_GUEST_MIXEDPSK',
    [
        'assoc_psk2_sta_guest',
        'assoc_psk_sta_guest',
        'assoc_tkippsk2_sta_guest',
        'assoc_tkippsk_sta_guest',
    ],
]


treeBSDApi = [
    'AP_MIXEDPSK_BSD',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_MIXEDPSK_BSD_SSIDSPEC',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_MIXEDPSK_BSD_KEYSPEC',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_MIXEDPSK_BSD_SSIDCHINESE',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_BSD_SSIDHIDE',
    [
        'ap_clear_ssidhide',
        'ap_psk2_ssidhide',
        'ap_mixedpsk_ssidhide',
    ],
    'AP_MIXEDPSK_BSD_SSIDHIDE',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta'
    ],
    'AP_MIXEDPSK_BSD_WHITELIST',
    [
        'assoc_psk2_near_field_sta_in_whitelist',
        'assoc_psk2_near_field_sta_outof_whitelist',
    ],
    'AP_MIXEDPSK_BSD_BLACKLIST',
    [
        'assoc_psk2_near_field_sta_in_blacklist',
        'assoc_psk2_near_field_sta_outof_blacklist',
    ],
    'AP_RELAY_MIXEDPSK_BSD',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_RELAY_BSD_SSIDHIDE',
    [
        'ap_clear_ssidhide',
        'ap_psk2_ssidhide',
        'ap_mixedpsk_ssidhide',
    ],
    'AP_RELAY_MIXEDPSK_BSD_SSIDHIDE',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_BSD',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
    'AP_WIRELESS_RELAY_BSD_SSIDHIDE',
    [
        'ap_clear_ssidhide',
        'ap_psk2_ssidhide',
        'ap_mixedpsk_ssidhide',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_BSD_SSIDHIDE',
    [
        'assoc_psk2_near_field_sta',
        'assoc_psk_near_field_sta',
        'assoc_tkippsk2_near_field_sta',
        'assoc_tkippsk_near_field_sta',
    ],
]


treeWireRelayApi = [
    'AP_RELAY_CLEAR_CHAN',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_RELAY_CLEAR_LOW',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_RELAY_CLEAR_MID',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_RELAY_CLEAR_HIGH',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_RELAY_CLEAR_LOW_TXPOWER',
    [
        'autochan_txpower_2g',
        'autochan_txpower_5g',
        'chan1_txpower_2g',
        'chan6_txpower_2g',
        'chan11_txpower_2g',
        'chan13_txpower_2g',
        'chan36_txpower_5g',
        'chan52_txpower_5g',
        'chan149_txpower_5g',
        'chan165_txpower_5g',
    ],
    'AP_RELAY_CLEAR_MID_TXPOWER',
    [
        'autochan_txpower_2g',
        'autochan_txpower_5g',
        'chan1_txpower_2g',
        'chan6_txpower_2g',
        'chan11_txpower_2g',
        'chan13_txpower_2g',
        'chan36_txpower_5g',
        'chan52_txpower_5g',
        'chan149_txpower_5g',
        'chan165_txpower_5g',
    ],
    'AP_RELAY_CLEAR_HIGH_TXPOWER',
    [
        'autochan_txpower_2g',
        'autochan_txpower_5g',
        'chan1_txpower_2g',
        'chan6_txpower_2g',
        'chan11_txpower_2g',
        'chan13_txpower_2g',
        'chan36_txpower_5g',
        'chan52_txpower_5g',
        'chan149_txpower_5g',
        'chan165_txpower_5g',
    ],
    'AP_RELAY_CLEAR_CHANSELECTION',
    [
        'chanselection_2g',
        'chanselection_5g',
    ],
    'AP_RELAY_PSK2',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk2_sta_5g',
    ],
    'AP_RELAY_MIXEDPSK',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_RELAY_MIXEDPSK_CHAN_BW80',
    [
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_RELAY_MIXEDPSK_CHAN_BW40',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_RELAY_MIXEDPSK_CHAN_BW20',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_RELAY_MIXEDPSK_SSIDSPEC',
    [
        'assoc_psk2_sta_ssidspec_2g',
        'assoc_psk_sta_ssidspec_2g',
        'assoc_tkippsk2_sta_ssidspec_2g',
        'assoc_tkippsk_sta_ssidspec_2g',
        'assoc_psk2_sta_ssidspec_5g',
        'assoc_psk_sta_ssidspec_5g',
        'assoc_tkippsk2_sta_ssidspec_5g',
        'assoc_tkippsk_sta_ssidspec_5g',
    ],
    'AP_RELAY_MIXEDPSK_KEYSPEC',
    [
        'assoc_psk2_sta_keyspec_2g',
        'assoc_psk_sta_keyspec_2g',
        'assoc_tkippsk2_sta_keyspec_2g',
        'assoc_tkippsk_sta_keyspec_2g',
        'assoc_psk2_sta_keyspec_5g',
        'assoc_psk_sta_keyspec_5g',
        'assoc_tkippsk2_sta_keyspec_5g',
        'assoc_tkippsk_sta_keyspec_5g',
    ],
    'AP_RELAY_MIXEDPSK_SSIDCHINESE',
    [
        'assoc_psk2_sta_ssidchinese_2g',
        'assoc_psk_sta_ssidchinese_2g',
        'assoc_tkippsk2_sta_ssidchinese_2g',
        'assoc_tkippsk_sta_ssidchinese_2g',
        'assoc_psk2_sta_ssidchinese_5g',
        'assoc_psk_sta_ssidchinese_5g',
        'assoc_tkippsk2_sta_ssidchinese_5g',
        'assoc_tkippsk_sta_ssidchinese_5g',
    ],
    'AP_RELAY_SSIDHIDE',
    [
        'ap_clear_ssidhide_2g',
        'ap_psk2_ssidhide_2g',
        'ap_mixedpsk_ssidhide_2g',
        'ap_clear_ssidhide_5g',
        'ap_psk2_ssidhide_5g',
        'ap_mixedpsk_ssidhide_5g',
    ],
    'AP_RELAY_MIXEDPSK_SSIDHIDE',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_RELAY_CONFIG_CHECK',
    [
        'config_check_2g',
        'config_check_5g',
        'config_check_guest',
    ],

]

treeAccessControlApi = [
    'AP_CLEAR_CHAN_WHITELIST',
    [
        'assoc_clear_sta_in_whitelist_2g',
        'assoc_clear_sta_outof_whitelist_2g',
        'assoc_clear_sta_in_whitelist_5g',
        'assoc_clear_sta_outof_whitelist_5g',
    ],

    'AP_CLEAR_CHAN_BLACKLIST',
    [
        'assoc_clear_sta_in_blacklist_2g',
        'assoc_clear_sta_outof_blacklist_2g',
        'assoc_clear_sta_in_blacklist_5g',
        'assoc_clear_sta_outof_blacklist_5g',
    ],
    'AP_GUEST_CLEAR_WHITELIST',
    [
        'assoc_clear_sta_in_whitelist_guest',
        'assoc_clear_sta_outof_whitelist_guest',
    ],

    'AP_GUEST_CLEAR_BLACKLIST',
    [
        'assoc_clear_sta_in_blacklist_guest',
        'assoc_clear_sta_outof_blacklist_guest',
    ],
    'AP_MIXEDPSK_WEB_ACCESS',
    [
        'assoc_psk2_sta_access_web_2g',
        'assoc_psk_sta_access_web_2g',
        'assoc_tkippsk_sta_access_web_2g',
        'assoc_tkippsk2_sta_access_web_2g',
        'assoc_psk2_sta_access_web_5g',
        'assoc_psk_sta_access_web_5g',
        'assoc_tkippsk_sta_access_web_5g',
        'assoc_tkippsk2_sta_access_web_5g',
    ],

]


treeWirelessRelayApi = [
    'AP_WIRELESS_RELAY_SCAN',
    [
        'scan_radio_on_2g',
        'scan_radio_off_2g'
    ],
    'AP_WIRELESS_RELAY_CLEAR_CHAN',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_WIRELESS_RELAY_CLEAR_LOW',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_WIRELESS_RELAY_CLEAR_MID',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_WIRELESS_RELAY_CLEAR_HIGH',
    [
        'assoc_clear_sta_2g',
        'assoc_clear_sta_5g',
    ],
    'AP_WIRELESS_RELAY_CLEAR_CHANSELECTION',
    [
        'chanselection_2g',
        'chanselection_5g',
    ],
    'AP_WIRELESS_RELAY_PSK2',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk2_sta_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_CHAN_BW80',
    [
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_CHAN_BW40',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_CHAN_BW20',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_SSIDSPEC',
    [
        'assoc_psk2_sta_ssidspec_2g',
        'assoc_psk_sta_ssidspec_2g',
        'assoc_tkippsk2_sta_ssidspec_2g',
        'assoc_tkippsk_sta_ssidspec_2g',
        'assoc_psk2_sta_ssidspec_5g',
        'assoc_psk_sta_ssidspec_5g',
        'assoc_tkippsk2_sta_ssidspec_5g',
        'assoc_tkippsk_sta_ssidspec_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_KEYSPEC',
    [
        'assoc_psk2_sta_keyspec_2g',
        'assoc_psk_sta_keyspec_2g',
        'assoc_tkippsk2_sta_keyspec_2g',
        'assoc_tkippsk_sta_keyspec_2g',
        'assoc_psk2_sta_keyspec_5g',
        'assoc_psk_sta_keyspec_5g',
        'assoc_tkippsk2_sta_keyspec_5g',
        'assoc_tkippsk_sta_keyspec_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_SSIDCHINESE',
    [
        'assoc_psk2_sta_ssidchinese_2g',
        'assoc_psk_sta_ssidchinese_2g',
        'assoc_tkippsk2_sta_ssidchinese_2g',
        'assoc_tkippsk_sta_ssidchinese_2g',
        'assoc_psk2_sta_ssidchinese_5g',
        'assoc_psk_sta_ssidchinese_5g',
        'assoc_tkippsk2_sta_ssidchinese_5g',
        'assoc_tkippsk_sta_ssidchinese_5g',
    ],
    'AP_WIRELESS_RELAY_SSIDHIDE',
    [
        'ap_clear_ssidhide_2g',
        'ap_psk2_ssidhide_2g',
        'ap_mixedpsk_ssidhide_2g',
        'ap_clear_ssidhide_5g',
        'ap_psk2_ssidhide_5g',
        'ap_mixedpsk_ssidhide_5g',
    ],
    'AP_WIRELESS_RELAY_MIXEDPSK_SSIDHIDE',
    [
        'assoc_psk2_sta_2g',
        'assoc_psk_sta_2g',
        'assoc_tkippsk2_sta_2g',
        'assoc_tkippsk_sta_2g',
        'assoc_psk2_sta_5g',
        'assoc_psk_sta_5g',
        'assoc_tkippsk2_sta_5g',
        'assoc_tkippsk_sta_5g',
    ],
    'AP_WIRELESS_RELAY_CONFIG_CHECK',
    [
        'config_check_2g',
        'config_check_5g',
        'config_check_guest',
    ],

]


treeQosApi = [
    'AP_QOS_MIXEDPSK',
    [
        'assoc_psk2_sta_speedtest_2g',
        'assoc_psk_sta_speedtest_2g',
        'assoc_tkippsk2_sta_speedtest_2g',
        'assoc_tkippsk_sta_speedtest_2g',
        'assoc_psk2_sta_speedtest_5g',
        'assoc_psk_sta_speedtest_5g',
        'assoc_tkippsk2_sta_speedtest_5g',
        'assoc_tkippsk_sta_speedtest_5g',
     ],
    'AP_QOS_CLEAR',
    [
        'assoc_clear_sta_speedtest_2g',
        'assoc_clear_sta_speedtest_5g',
    ],
    'AP_QOS_PSK2',
    [
        'assoc_psk2_sta_speedtest_2g',
        'assoc_psk2_sta_speedtest_5g',
    ],
    'AP_QOS_GUEST_MIXEDPSK',
    [
        'assoc_psk2_sta_speedtest_guest',
        'assoc_psk_sta_speedtest_guest',
        'assoc_tkippsk2_sta_speedtest_guest',
        'assoc_tkippsk_sta_speedtest_guest',
    ]
]

treeThroughputDUTApi = [
    "AP_CLEAR_CHAN1_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN6_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN11_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN13_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN1_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN6_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN11_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN13_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN1_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN6_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN11_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN13_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN1_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN6_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN11_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN13_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN36_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN165_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN36_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN44_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN60_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN157_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN36_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN165_BW20_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN44_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN60_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN157_BW40_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW80_DUT_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
]

treeThroughputLANApi = [
    "AP_CLEAR_CHAN1_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN6_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN11_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN13_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN1_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN6_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN11_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN13_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN1_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN6_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN11_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN13_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN1_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN6_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN11_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_PSK2_CHAN13_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_2g",
    ],
    "AP_CLEAR_CHAN36_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN165_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN36_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN44_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN60_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN157_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN36_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN52_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_CLEAR_CHAN149_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN165_BW20_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN44_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN60_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN157_BW40_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN36_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN52_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
    "AP_PSK2_CHAN149_BW80_LAN_THROUGHPUT",
    [
        "assoc_sta_throughput_5g",
    ],
]

treeOthersApi = [
    'AP_CHECK',
    [
        'check_ap_reboot_lastestpower',
        'check_ap_upgrade_lastestpower',
        'check_ap_reset_lastestpower',
    ]
]

treeStressApi = [
    "AP_CLEAR_CHAN_REPEAT",
    [
        "assoc_repeat_clear_sta_2g",
        "assoc_repeat_clear_sta_5g"
    ],
    "AP_PSK2_CHAN_REPEAT",
    [
        "assoc_repeat_psk2_sta_2g",
        "assoc_repeat_psk2_sta_5g",
    ],
    "AP_MIXEDPSK_CHAN_REPEAT",
    [
        "assoc_repeat_psk2_sta_2g",
        "assoc_repeat_psk_sta_2g",
        "assoc_repeat_tkippsk2_sta_2g",
        "assoc_repeat_tkippsk_sta_2g",
        "assoc_repeat_psk2_sta_5g",
        "assoc_repeat_psk_sta_5g",
        "assoc_repeat_tkippsk2_sta_5g",
         "assoc_repeat_tkippsk_sta_5g",
    ],
    "AP_GUEST_CLEAR_REPEAT",
    [
        "assoc_repeat_clear_sta_guest",
    ],
    "AP_GUEST_MIXEDPSK_REPEAT",
    [
        "assoc_repeat_psk2_sta_guest",
        "assoc_repeat_psk_sta_guest",
        "assoc_repeat_tkippsk2_sta_guest",
        "assoc_repeat_tkippsk_sta_guest",
    ],
    "AP_GUEST_PSK2_REPEAT",
    [
        "assoc_repeat_psk2_sta_guest",
    ],
]

# -------------------------------------------------------







